### ISSUE TITLE
Restricting languages

### ISSUE THREAD

**Issue by jocubeit** [grosser/countries_and_languages#1]
Hi I just wanted to ask what might be the best way to restrict the list of languages to those defined in `I18n.available_locales`?

**Comment by jocubeit** [comment]
Ok, found a solution, probably not the most elegant but it works. Let me know if you have a better way to achieve this.

```ruby
languages.select { |el| el[1].downcase.to_sym.in?(I18n.available_locales) }
```

`I18n.available_locales` must be set in an initializer obviously, and code assumes that the locales passed to `available_locales` method are lowercase symbols.

I'll let you make a decision on closing.

**Comment by grosser** [comment]
Looks good.
I'd recommend avoiding calling I18n.available_locales multiple times by storing it in a local variable.
